app/urls.py
from django.urls import path,include
from .import views
 
urlpatterns = [
    path('',views.home,name="home"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('app.urls','app'),namespace='app'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.conf import settings
from django.db import models

# Create your models here.

class product(models.Model):
    name = models.CharField(max_length=250)
    image = models.ImageField(upload_to="images")
    description = models.CharField(max_length=250)

    def __str__(self) -> str:
        return str(self.name)

app/views.py
from django.shortcuts import render
from .models import product
from .documents import ProductDocument
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from elasticsearch_dsl.query import Q

@csrf_exempt
def home(request):
    if request.method == "POST":
        name = request.POST.get('name','')
        data = ProductDocument.search().query(Q("match",name=name) | Q("match",description=name))
        data= data.to_queryset().values()
        return JsonResponse(list(data),safe=False)

    data = ProductDocument.search().query(Q("match_phrase",name="madaa") | Q("match",description="eye"))
    # print("########",data)
    return render(request,"app/articles.html",{"product":data})

app/templates/app/articles.html
{% extends 'app/base.html' %}
{% load static %}
{% block feature %}
<div class = "container">
    <div class = "title">
      <h2>All Articles</h2>
    </div>
    <form method="POST" id="btn">
      <input type="text" id="query" name="query" class="textbox" placeholder="Search">
      <button type = "submit" class="button">
        <i class='bx bx-search'></i>
      </button>
    </form>
    <div class="article-meta">
        <a class="back-button" href="{% url 'app:home' %}">All Articles</a>
        {% for tag in tags %}
        <span class="tag"><a href="#">{{ tag.name }}</a></span>
        {% endfor %}
    </div>

    <hr>
    <div class = "featured-content">
  
      <div class = "featured-item">
        <div class = "featured-img">
            <p id="out-data"></p>
            
        </div>
      </div>
    
    </div>
</div>
{% endblock feature %}

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bloggies</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Boxicon awesome icon -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"">
    <style type="text/css">
        img{
          max-width: 100%;
          object-fit: cover;
        }
      
        .featured_image{
          margin-top: 20px;
          margin-bottom: 20px;
        }
      
        .post-container{
            width: 900px;
            margin: 0 auto;
            padding-top: 20px;
            padding-bottom: 20px;
        }
      
        .author-pic{
          width: 50px;
          height: 50px;
          border-radius: 50%;
          margin-right: 10px;
        }
      
        @media screen and (max-width: 900px){
          .post-container{
            width: 95%;
          }
        }
      </style>
  </head>
  <body>

    <!-- header -->
      <nav class = "navbar">
        <div class = "container">
          <a href = "{% url 'app:home' %}" class = "navbar-brand">{{ name }} Blog</a>
          <div class = "navbar-nav">
            <a href = "{% url 'app:home' %}">home</a>
          
            <a href = "">about</a>
          </div>
        </div>
      </nav>
      {% block base_banner %} {% endblock base_banner %}
    <!-- end of header -->
    
    <!-- featured -->
    {% block feature %} {% endblock feature %}
    <!-- end of featured -->

    <!-- about -->
    {% block about %} {% endblock about %}
    <!-- end of about -->

    <!-- footer -->
    <footer>
      <div class = "social-links">
        <a href = "#"><i class='bx bxl-facebook'></i></a>
        <a href = "#"><i class='bx bxl-twitter'></i></a>
        <a href = "#"><i class='bx bxl-instagram'></i></a>
        <a href = "#"><i class='bx bxl-github'></i></a>
      </div>
      <span>Bloggies</span>
    </footer>
    <!-- end of footer -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/myscript.js' %}"></script>
  </body>
</html>